<?php
/**
 * Copyright © 2015 WideFocus. All rights reserved.
 * http://www.widefocus.net
 *
 * @var WideFocus_WidgetPreviews_Block_Widget_Preview $this
 */
?>
<div class="wrapper">
    <div class="page">
        <div class="main-container col1-layout">
            <div class="main">
                <div class="col-main">
                    <div class="std"><?php echo $this->getPreview() ?></div>
                </div>
            </div>
        </div>
    </div>
</div>

